package dreamersweekend.salience.statuscode;

public enum StatusCodeName {
	
	BASE_IMAGE_FOUND,
	BASE_IMAGE_NOT_FOUND,
	CURRENT_IMAGE_FOUND,
	CURRENT_IMAGE_NOT_FOUND,
	BASE_URL_FOUND,
	BASE_URL_NOT_FOUND,
	CURRENT_URL_FOUND,
	CURRENT_URL_NOT_FOUND,
	BASE_CURRENT_IMAGES_NOT_FOUND,
	EXTREMELY_INCOMPATIBLE_IMAGES,
	MATCHED_IMAGES,
	MISMATCHED_IMAGES
}
